_git_log_medium_format='%C(bold)Commit:%C(reset) %C(green)%H%C(red)%d%n%C(bold)Author:%C(reset) %C(cyan)%an <%ae>%n%C(bold)Date:%C(reset)   %C(blue)%ai (%ar)%C(reset)%n%+B'
_git_log_oneline_format='%C(green)%h%C(reset) %s%C(red)%d%C(reset)%n'

function git-branch-current {
  git rev-parse --abbrev-ref HEAD
}

alias gb='git branch'
alias gbc='git checkout -b'
alias gbl='gb -v'
alias gbx='gb -d'
alias gbX='gb -D'
alias gc='git commit --verbose'
alias gcm='git commit --message'
alias gco='git checkout'
alias gcf='git commit --amend --reuse-message HEAD'
alias gcF='gc --amend'
alias gcr='git revert'
alias gcR='git reset "HEAD^"'
alias gf='git fetch'
alias gfc='git clone'
alias gfr='git pull --rebase'
alias gia='git add'
alias giA='gia --patch'
alias gid='git diff --no-ext-diff --cached'
alias gir='git reset'
alias giR='gir --patch'
alias gix='git rm -r --cached'
alias giX='gix -f'
alias gl='git log --topo-order --pretty=format:"${_git_log_medium_format}"'
alias gls='gl --stat'
alias gld='gls --patch'
alias glo='git log --topo-order --pretty=format:"${_git_log_oneline_format}"'
alias gm='git merge'
alias gmF='gm --no-ff'
alias gma='gm --abort'
alias gmt='git mergetool'
alias gp='git push'
alias gpf='gp --force'
alias gpa='gp --all'
alias gpc='gp --set-upstream origin "$(git-branch-current 2> /dev/null)"'
alias gr='git rebase'
alias gra='gr --abort'
alias grc='gr --continue'
alias gri='gr --interactive'
alias grs='gr --skip'
alias gs='git stash'
alias gsa='gs apply'
alias gsx='gs drop'
alias gsl='gs list'
alias gsd='gs show --patch --stat'
alias gsp='gs pop'
alias gws='git status --short'
alias gwd='git diff --no-ext-diff'
alias gwr='gir --soft'
alias gwR='gir --hard'
alias gwc='git clean -n'
alias gwC='git clean -f'
alias gwx='git rm -r'
alias gwX='gwx -f'
